site_name: Ultra documentation
site_description: Documentation for building apps on Flipkart Ultra platform
pages:
    - Home: index.md
    - Tutorial : tutorial.md
    - Onboarding: onboarding.md
    - Flow diagrams : flows.md
    - Client Side API: clients.md
    - Server Side API:
        - Basic APIs: backend.md
        - OMS: oms.md
    - Demo: demo.md
    - Contact Us : contact.md
    - Announcements :
        - All Announcements : announcement.md
        - Migrating ClientId : migrating-clientid.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition:
