site_name: Ultra
site_description: A technical guide for building applications with Flipkart using Ultra platform
pages:
    - Overview: index.md
    - Getting Started : 
        - Learn the basics: terms.md
        - Terminology: terms.md
    - Basic Guidelines and Checklist: checklist.md
    - Integration with Ultra : 
        - Steps: integrate.md
        - API Details : 
            - Client APIs: clients.md
            - Server APIs: backend.md
        - Ultra Demo: demo.md
    - Troubleshooting: troubleshoot.md
    - FAQs: faq.md
    - Contact Us: contact.md
    - News and Announcements: announcement.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition:
