site_name: Ultra
site_description: A technical guide for building applications with Flipkart using Ultra platform
pages:
    - Home: index.md
    - Tutorial : tutorial.md
    - Flow diagrams : flows.md
    - Client Side API: clients.md
    - Server Side API:
        - Basic APIs: backend.md
        - OMS: oms.md
    - Demo: demo.md
    - Contact Us : contact.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition:
