site_name: Ultra documentation
pages:
    - Home: index.md
    - Onboarding: onboarding.md
    - User guide : userguide.md
    - Client Side API: clients.md
    - Server Side API: backend.md

theme:
  name: 'material'