site_name: Ultra
site_description: A technical guide for building applications with Flipkart using Ultra platform
pages:
    - Home: index.md
    - Tutorial : tutorial.md
    - Onboarding: onboarding.md
    - Flow diagrams : flows.md
    - Client Side API: 
        - Basic APIs: clients.md
        - Analytics :
            - Overview : analytics-overview.md
            - Travel : analytics-travel.md
    - Server Side API:
        - Basic APIs: backend.md
        - OMS: oms.md
    - Demo: demo.md
    - Contact Us : contact.md
    - Announcements :
        - All Announcements : announcement.md
        - Migrating ClientId : migrating-clientid.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition:
