site_name: Ultra documentation
pages:
    - Home: index.md
    - Tutorial : tutorial.md
    - Onboarding: onboarding.md
    - Flow diagrams : flows.md
    - Client Side API: clients.md
    - Server Side API: backend.md
    - OMS: oms.md
    - Demo: demo.md
    - Contact Us : contact.md
    - Annonucements : announcement.md
theme:
  name: 'material'
markdown_extensions:
  - codehilite
